name: Release Changelog

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run release-please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          default-branch: main
          include-component-in-tag: false
